pub(super) const PALO_ALTO_HEADERS: &[&str] = &[
    "Log Number",
    "Receive Time",
    "Serial Number",
    "Type",
    "Threat/Content Type",
    "Config Version",
    "Generated Time",
    "Source address",
    "Destination address",
    "NAT source IP",
    "NAT destination IP",
    "Rule Name",
    "Source User",
    "Destination User",
    "Application",
    "Virtual System",
    "Source Zone",
    "Destination Zone",
    "Inbound Interface",
    "Outbound Interface",
    "Log Action",
    "Time Logged",
    "Session ID",
    "Repeat Count",
    "Source Port",
    "Destination Port",
    "NAT Source Port",
    "NAT Destination Port",
    "Flags",
    "IP Protocol",
    "Action",
    "Bytes",
    "Bytes Sent",
    "Bytes Received",
    "Packets",
    "Start Time",
    "Elapsed Time in seconds",
    "Category",
    "Padding",
    "Sequence Number",
    "Action Flags",
    "Source Location",
    "Destination Location",
    "Padding-2",
    "Packets Sent",
    "Packets Received",
    "Session End Reason",
    "Device Group Hierarchy Level 1",
    "Device Group Hierarchy Level 2",
    "Device Group Hierarchy Level 3",
    "Device Group Hierarchy Level 4",
    "Virtual System Name",
    "Device Name",
    "Action Source",
    "Source VM UUID",
    "Destination VM UUID",
    "Tunnel ID/IMSI",
    "Monitor Tag/IMEI",
    "Parent Session ID",
    "Parent Start Time",
    "Tunnel Type",
    "SCTP Association ID",
    "SCTP Chunks",
    "SCTP Chunks Sent",
    "SCTP Chunks Received",
    "UUID for rule",
    "HTTP/2 Connection",
    "Application-Level-Link-Changes",
    "Policy-ID",
    "Link-Switches",
    "SD-WAN-Cluster",
    "SD-WAN-Device-Type",
    "SD-WAN-Cluster-Type",
    "SD-WAN-Site",
    "Dynamic-User-Group-Name",
    "X-Forwarded-For-Address",
    "Source-Device-Category",
    "Source-Device-Profile",
    "Source-Device-Model",
    "Source-Device-Vendor",
    "Source-Device-OS-Family",
    "Source-Device-OS-Version",
    "Source-Hostname",
    "Source-MAC-Address",
    "Destination-Device-Category",
    "Destination-Device-Profile",
    "Destination-Device-Model",
    "Destination-Device-Vendor",
    "Destination-Device-OS-Family",
    "Destination-Device-OS-Version",
    "Destination-Hostname",
    "Destination-MAC-Address",
    "Container-ID",
    "POD-Namespace",
    "POD-Name",
    "Source-External-Dynamic-List",
    "Destination-External-Dynamic-List",
    "Host-ID",
    "User-Device-Serial-Number",
    "Source-Dynamic-Address-Group",
    "Destination-Dynamic-Address-Group",
    "Session-Owner",
    "High-Resolution-Timestamp",
    "A-Slice-Service-Type",
    "A-Slice-Differentiator",
    "Application-Subcategory",
    "Application-Category",
    "Application-Technology",
    "Application-Risk",
    "Application-Characteristics",
    "Application-Container-Name",
    "Tunneled-Application",
    "is-SAAS-App",
    "Application-Sanctioned-State",
    "Offloaded",
];

pub(super) const INTEGER_FIELDS: &[&str] = &[
    "Log Number",
    "Config Version",
    "Session ID",
    "Repeat Count",
    "Source Port",
    "Destination Port",
    "NAT Source Port",
    "NAT Destination Port",
    "Bytes",
    "Bytes Sent",
    "Bytes Received",
    "Packets",
    "Elapsed Time in seconds",
    "Sequence Number",
    "Packets Sent",
    "Packets Received",
    "Policy-ID",
    "Link-Switches",
    "Application-Risk",
];

pub(super) const FLOAT_FIELDS: &[&str] = &["High-Resolution-Timestamp"];
