[package]
name = "wazuh_forwarder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
crossbeam-channel = "0.5"
fern = { version = "0.7", features = ["colored"] }
lazy_static = "1.4"
log = "0.4"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3"
sha2 = "0.10"  # Added missing dependency